### ISSUE TITLE
DistCp uses internal IP addresses

### ISSUE THREAD

**Issue by jakubaugustin** [jakubaugustin/SEBC#5]
After running distcp job using CM we experienced problem with HDFS providing us with internal IPs.

All the mapreduce jobs failed with:
```
org.apache.hadoop.net.ConnectTimeoutException: 69000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/172.31.33.149:50010]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:533)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.hdfs.DFSClient.connectToDN(DFSClient.java:2408)
	at org.apache.hadoop.hdfs.DFSClient.getFileChecksum(DFSClient.java:2268)
	at org.apache.hadoop.hdfs.DistributedFileSystem$23.doCall(DistributedFileSystem.java:1337)
	at org.apache.hadoop.hdfs.DistributedFileSystem$23.doCall(DistributedFileSystem.java:1333)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileChecksum(DistributedFileSystem.java:1333)
	at com.cloudera.enterprise.distcp.util.DistCpUtils.getFileChecksum(DistCpUtils.java:375)
	at com.cloudera.enterprise.distcp.mapred.RetriableFileCopyCommand.doExecute(RetriableFileCopyCommand.java:118)
	at com.cloudera.enterprise.distcp.util.RetriableCommand.execute(RetriableCommand.java:87)
	at com.cloudera.enterprise.distcp.mapred.CopyMapper.copyFileWithRetry(CopyMapper.java:510)
	at com.cloudera.enterprise.distcp.mapred.CopyMapper.map(CopyMapper.java:368)
	at com.cloudera.enterprise.distcp.mapred.CopyMapper.map(CopyMapper.java:61)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1783)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by jakubaugustin** [comment]
Issue resolved by using HDFS multihoming setup as described in: https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HdfsMultihoming.html
